export declare const GREEN = "#11c2bc";
export declare const SCRIPT_EXTS: string[];
export declare const STYLE_EXTS: string[];
export declare const projectDir: string;
export declare const COMPONENTS_JSON: string;
export declare const DIST: string;
export declare const outerConfigDir: string;
export declare const cacheDir: string;
export declare const srcDir: string;
export declare const postcssDir: string;
export declare const jestDir: string;
export declare const DIST_DIR: string;
export declare const SITE_DESKTOP_SHARED_FILE: string;
export declare const SITE_MOBILE_SHARED_FILE: string;
export declare const PACKAGE_JSON_FILE: string;
export declare const ROUTES_FILE: string;
export declare const MOBILE_ROUTES_FILE: string;
export declare const COMPONENTS_FILE: string;
export declare const COMPONENTS_ENTRY: string;
export declare const DIST_COMPONENTS_ENTRY: string;
export declare const COMPONENTS_COMMON_STYLE: string;
export declare const DIST_COMPONENTS_COMMON_STYLE: (env: any) => string;
export declare const CONFIG_DIR: string;
export declare const JEST_CONFIG_FILE: string;
export declare const VETUR_DIR: string;
